export type OptionalCampoSection = "A2" | "G" | "E";
export type OptionalListaSection = "B2" | "D" | "G1" | "G2" | "G3" | "G4" | "G5" | "G11";
export type SupportedSection = "A" | "B" | OptionalCampoSection | OptionalListaSection;

// Controla qué secciones opcionales se van a incluir en el payload.
export const OPTIONAL_CAMPO_SECTIONS: readonly OptionalCampoSection[] = ["A2", "G", "E"];
export const OPTIONAL_LISTA_SECTIONS: readonly OptionalListaSection[] = [
    "B2",
    "D",
    "G1",
    "G2",
    "G3",
    "G4",
    "G5",
    "G11",
];

// Catálogo central de nombres de campos esperados por sección.
// Puedes editar esta lista cuando cambie el contrato del backend.
export const SECTION_FIELD_NAMES: Record<SupportedSection, readonly string[]> = {
    A: [
        "CODI_EMPR",
        "TipoDTE",
        "Serie",
        "Correlativo",
        "FchEmis",
        "HoraEmision",
        "TipoMoneda",
        "TipoRucEmis",
        "RUTEmis",
        "RznSocEmis",
        "CodigoLocalAnexo",
        "TipoRutReceptor",
        "RUTRecep",
        "RznSocRecep",
        "DirRecep",
        "TipoOperacion",
        "MntNeto",
        "MntExe",
        "MntExo",
    ],
    B: ["NroLinDet", "QtyItem", "UnmdItem", "NmbItem", "MontoItem", "CodigoTipoIgv", "TasaIgv", "ImpuestoIgv"],
    A2: ["CodigoImpuesto", "MontoImpuesto", "TasaImpuesto", "MontoImpuestoBase"],
    B2: ["NroLinDet", "QtyItem", "UnmdItem", "NmbItem"],
    D: ["NroLinRef", "DescTpoDocRef", "TpoDocRef", "SerieRef", "FolioRef", "TipoRucEmisDocRef", "RucEmisDocRef"],
    E: ["TipoAdicSunat", "NmrLineasDetalle", "NmrLineasAdicSunat", "DescripcionAdicsunat"],
    G: [
        "Observaciones",
        "IdentifTraslado",
        "MotivoTraslado",
        "DescTraslado",
        "PesoBrutoTotItemsSel",
        "SustentoDifPeso",
        "TotalPesoTraslado",
        "UnmdTotalPeso",
        "NroBultos",
        "EntEmisoraRemi",
        "NumAutorizRemi",
        "PlacaVehicPrinc",
        "CertHabVehicularPrinc",
        "EntEmisoraVehPrinc",
        "NumAutorizVehPrinc",
        "RucTercero",
        "TipoRucTercero",
        "RazonTercero",
        "RucProveedor",
        "TipoRucProveedor",
        "RazonProveedor",
        "RucComprador",
        "TipoRucComprador",
        "RazonComprador",
        "RucRemitente",
        "TipoRucRemitente",
        "RazonRemitente",
        "RucSubcontratador",
        "TipoRucSubcontratador",
        "RazonSubcontratador",
        "RucPagaTransporte",
        "TipoRucPagaTransporte",
        "RazonPagaTransporte",
        "DirParUbiGeo",
        "DirParDireccion",
        "RucPuntoPartida",
        "CodigoLocalPartida",
        "PuntoGeorefPartidaLat",
        "PuntoGeorefPartidaLon",
        "DirLlegUbiGeo",
        "DirLlegDireccion",
        "RucPuntoLlegada",
        "CodigoLocalLlegada",
        "PuntoGeorefLlegadaLat",
        "PuntoGeorefLlegadaLon",
    ],
    G1: [
        "NroLinTramo",
        "ModalidadTraslado",
        "FechInicioTraslado",
        "RucTranspor",
        "TipoRucTrans",
        "RazoTrans",
        "NumRegMTC",
        "EntEmisoraTransp",
        "NumAutorizTransp",
    ],
    G2: ["NroLinPuertoAerop", "IdPuertoAerop", "NmbPuertoAerop", "TipoPuertoAerop"],
    G3: ["NroLinContenedor", "IdContenedor", "NumPrecinto"],
    G4: ["NroLinIndicadorTrasl", "IndicadorTraslado"],
    G5: ["NroLinVehSec", "PlacaVehicSec", "CertHabVehicularSec", "EntEmisoraVehSec", "NumAutorizVehPrinc"],
    G11: [
        "NroLinConductor",
        "TipoConductor",
        "ConductorNroDocId",
        "ConductorTipoDocId",
        "NombConductor",
        "ApellConductor",
        "NumLicenciaCond",
    ],
};

// Plantillas JSON por sección para documentar rápidamente qué enviar.
export const SECTION_JSON_TEMPLATE: Record<SupportedSection, Record<string, string> | Array<Record<string, string>>> = {
    A: {
        CODI_EMPR: "1",
        TipoDTE: "01",
        Serie: "F001",
        Correlativo: "1",
        FchEmis: "2026-03-30",
        HoraEmision: "10:30:00",
        TipoMoneda: "PEN",
        TipoRucEmis: "6",
        RUTEmis: "20123456789",
        RznSocEmis: "EMPRESA DEMO SAC",
        CodigoLocalAnexo: "0000",
        TipoRutReceptor: "6",
        RUTRecep: "20555555555",
        RznSocRecep: "CLIENTE DEMO SAC",
        DirRecep: "AV DEMO 123",
        TipoOperacion: "0101",
        MntNeto: "100.00",
        MntExe: "0.00",
        MntExo: "0.00",
    },
    B: [
        {
            NroLinDet: "1",
            QtyItem: "1",
            UnmdItem: "NIU",
            NmbItem: "PRODUCTO DEMO",
            MontoItem: "100.00",
            CodigoTipoIgv: "1000",
            TasaIgv: "18",
            ImpuestoIgv: "18.00",
        },
    ],
    A2: {
        CodigoImpuesto: "1000",
        MontoImpuesto: "18.00",
        TasaImpuesto: "18.00",
        MontoImpuestoBase: "100.00",
    },
    B2: [
        {
            NroLinDet: "1",
            QtyItem: "1",
            UnmdItem: "NIU",
            NmbItem: "PRODUCTO DEMO",
        },
    ],
    D: [
        {
            NroLinRef: "1",
            DescTpoDocRef: "Factura",
            TpoDocRef: "01",
            SerieRef: "F001",
            FolioRef: "123",
            TipoRucEmisDocRef: "6",
            RucEmisDocRef: "20123456789",
        },
    ],
    E: {
        TipoAdicSunat: "",
        NmrLineasDetalle: "0",
        NmrLineasAdicSunat: "0",
        DescripcionAdicsunat: "",
    },
    G: {
        Observaciones: "",
        IdentifTraslado: "",
        MotivoTraslado: "",
        DescTraslado: "",
        PesoBrutoTotItemsSel: "",
        SustentoDifPeso: "",
        TotalPesoTraslado: "",
        UnmdTotalPeso: "",
        NroBultos: "",
        EntEmisoraRemi: "",
        NumAutorizRemi: "",
        PlacaVehicPrinc: "",
        CertHabVehicularPrinc: "",
        EntEmisoraVehPrinc: "",
        NumAutorizVehPrinc: "",
        RucTercero: "",
        TipoRucTercero: "",
        RazonTercero: "",
        RucProveedor: "",
        TipoRucProveedor: "",
        RazonProveedor: "",
        RucComprador: "",
        TipoRucComprador: "",
        RazonComprador: "",
        RucRemitente: "",
        TipoRucRemitente: "",
        RazonRemitente: "",
        RucSubcontratador: "",
        TipoRucSubcontratador: "",
        RazonSubcontratador: "",
        RucPagaTransporte: "",
        TipoRucPagaTransporte: "",
        RazonPagaTransporte: "",
        DirParUbiGeo: "",
        DirParDireccion: "",
        RucPuntoPartida: "",
        CodigoLocalPartida: "",
        PuntoGeorefPartidaLat: "",
        PuntoGeorefPartidaLon: "",
        DirLlegUbiGeo: "",
        DirLlegDireccion: "",
        RucPuntoLlegada: "",
        CodigoLocalLlegada: "",
        PuntoGeorefLlegadaLat: "",
        PuntoGeorefLlegadaLon: "",
    },
    G1: [
        {
            NroLinTramo: "1",
            ModalidadTraslado: "01",
            FechInicioTraslado: "2026-03-30",
            RucTranspor: "20123456789",
            TipoRucTrans: "6",
            RazoTrans: "TRANSPORTES DEMO SAC",
            NumRegMTC: "",
            EntEmisoraTransp: "",
            NumAutorizTransp: "",
        },
    ],
    G2: [
        {
            NroLinPuertoAerop: "1",
            IdPuertoAerop: "",
            NmbPuertoAerop: "",
            TipoPuertoAerop: "",
        },
    ],
    G3: [
        {
            NroLinContenedor: "1",
            IdContenedor: "",
            NumPrecinto: "",
        },
    ],
    G4: [
        {
            NroLinIndicadorTrasl: "1",
            IndicadorTraslado: "",
        },
    ],
    G5: [
        {
            NroLinVehSec: "1",
            PlacaVehicSec: "",
            CertHabVehicularSec: "",
            EntEmisoraVehSec: "",
            NumAutorizVehPrinc: "",
        },
    ],
    G11: [
        {
            NroLinConductor: "1",
            TipoConductor: "",
            ConductorNroDocId: "",
            ConductorTipoDocId: "",
            NombConductor: "",
            ApellConductor: "",
            NumLicenciaCond: "",
        },
    ],
};
