package com.facturacion.api.core.catalogo;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum UnidadDeMedida {
    _4A("4A", "BOBINAS"),
    BJ("BJ", "BALDE"),
    BLL("BLL", "BARRILES"),
    BG("BG", "BOLSA"),
    BO("BO", "BOTELLAS"),
    BX("BX", "CAJA"),
    CT("CT", "CARTONES"),
    CMK("CMK", "CENTIMETRO CUADRADO"),
    CMQ("CMQ", "CENTIMETRO CUBICO"),
    CMT("CMT", "CENTIMETRO LINEAL"),
    CEN("CEN", "CIENTO DE UNIDADES"),
    CY("CY", "CILINDRO"),
    CJ("CJ", "CONOS"),
    DZN("DZN", "DOCENA"),
    DZP("DZP", "DOCENA POR 10**6"),
    BE("BE", "FARDO"),
    GLI("GLI", "GALON INGLES (4,545956L)"),
    GRM("GRM", "GRAMO"),
    GRO("GRO", "GRUESA"),
    HLT("HLT", "HECTOLITRO"),
    LEF("LEF", "HOJA"),
    SET("SET", "JUEGO"),
    KGM("KGM", "KILOGRAMO"),
    KTM("KTM", "KILOMETRO"),
    KWH("KWH", "KILOVATIO HORA"),
    KT("KT", "KIT"),
    CA("CA", "LATAS"),
    LBR("LBR", "LIBRAS"),
    LTR("LTR", "LITRO"),
    MWH("MWH", "MEGAWATT HORA"),
    MTR("MTR", "METRO"),
    MTK("MTK", "METRO CUADRADO"),
    MTQ("MTQ", "METRO CUBICO"),
    MGM("MGM", "MILIGRAMOS"),
    MLT("MLT", "MILILITRO"),
    MMT("MMT", "MILIMETRO"),
    MMK("MMK", "MILIMETRO CUADRADO"),
    MMQ("MMQ", "MILIMETRO CUBICO"),
    MLL("MLL", "MILLARES"),
    UM("UM", "MILLON DE UNIDADES"),
    ONZ("ONZ", "ONZAS"),
    PF("PF", "PALETAS"),
    PK("PK", "PAQUETE"),
    PR("PR", "PAR"),
    FOT("FOT", "PIES"),
    FTK("FTK", "PIES CUADRADOS"),
    FTQ("FTQ", "PIES CUBICOS"),
    C62("C62", "PIEZAS"),
    PG("PG", "PLACAS"),
    ST("ST", "PLIEGO"),
    INH("INH", "PULGADAS"),
    RM("RM", "RESMA"),
    DR("DR", "TAMBOR"),
    STN("STN", "TONELADA CORTA"),
    LTN("LTN", "TONELADA LARGA"),
    TNE("TNE", "TONELADAS"),
    TU("TU", "TUBOS"),
    NIU("NIU", "UNIDAD (BIENES)"),
    ZZ("ZZ", "UNIDAD (SERVICIOS)"),
    GLL("GLL", "US GALON (3,7843 L)"),
    YRD("YRD", "YARDA"),
    YDK("YDK", "YARDA CUADRADA");

    private final String codigo;
    private final String descripcion;
}
